version: "3.9"

services:
  web:
    container_name: ${APP_NAME}-web
    build:
      context: ./.docker/web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_CONNECTION}
    depends_on:
      - mysql
  mysql:
    container_name: ${APP_NAME}-mysql
    build:
      context: ./.docker/database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
  valkey:
    image: "valkey/valkey:7.2"
    container_name: ${APP_NAME}-valkey
    ports:
      - "6379:6379"
